### ISSUE TITLE
Saving test reports

### ISSUE THREAD

**Issue by pkriens** [bndtools/bnd#4493]
I just found out that it is possible to save the test reports from a build. Github Actions have the concept of _artifacts_. You can upload a part of the build files to artifacts and you can download this on the build instance page. They do not provide a direct link to a file system, for obvious reasons.

You can activate this by adding a new step:
```
 - name: save-tests
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '*/target/reports/**'
```
Since I am not clear how the matrix build works, I'd ask humbly if our fearless leader can integrate this in the build?
